In [1]:
import nltk
import pandas as pd
import string

nltk.download_shell()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------

Downloader>  l

Packages:
  [ ] abc................. Australian Broadcasting Commission 2006
  [ ] alpino.............. Alpino Dutch Treebank
  [ ] averaged_perceptron_tagger Averaged Perceptron Tagger
  [ ] averaged_perceptron_tagger_eng Averaged Perceptron Tagger (JSON)
  [ ] averaged_perceptron_tagger_ru Averaged Perceptron Tagger (Russian)
  [ ] averaged_perceptron_tagger_rus Averaged Perceptron Tagger (Russian)
  [ ] basque_grammars..... Grammars for Basque
  [ ] bcp47............... BCP-47 Language Tags
  [ ] biocreative_ppi..... BioCreAtIvE (Critical Assessment of Information
                           Extraction Systems in Biology)
  [ ] bllip_wsj_no_aux.... BLLIP Parser: WSJ Model
  [ ] book_grammars....... Grammars from NLTK Book
  [ ] brown............... Brown Corpus
  [ ] brown_tei........... Brown Corpus (TEI XML Version)
  [ ] cess_cat............ CESS-CAT Treebank
  [ ] cess_esp............ CESS-ESP Treebank
  [ ] chat80.............. Chat-80 Data Files
  [ ] city_database....... City Database
  [ ] cmudict............. The Carnegie Mellon Pronouncing Dictionary (0.6)
  [ ] comparative_sentences Comparative Sentence Dataset

Hit Enter to continue:  q

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------

Downloader>  q

In [24]:
messages = [line.rstrip() for line in open('/home/oem/spam.csv',encoding='latin-1')]

In [25]:
print(messages[0])

v1,v2,,,

In [26]:
print(len(messages))

5575

In [27]:
for mess_no, message in enumerate(messages[:10]):
    print(mess_no,message)
    print('\n')

0 v1,v2,,,


1 ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",,,


2 ham,Ok lar... Joking wif u oni...,,,


3 spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's,,,


4 ham,U dun say so early hor... U c already then say...,,,


5 ham,"Nah I don't think he goes to usf, he lives around here though",,,


6 spam,"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv",,,


7 ham,Even my brother is not like to speak with me. They treat me like aids patent.,,,


8 ham,As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune,,,


9 spam,WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.,,,

In [28]:
import pandas as pd

In [29]:
messages = pd.read_csv(
    '/home/oem/spam.csv',
    sep='\t',
    names=['label', 'message'],
    encoding='latin-1'
)

messages.head()

                                               label  message
0                                           v1,v2,,,      NaN
1  ham,"Go until jurong point, crazy.. Available ...      NaN
2               ham,Ok lar... Joking wif u oni...,,,      NaN
3  spam,Free entry in 2 a wkly comp to win FA Cup...      NaN
4  ham,U dun say so early hor... U c already then...      NaN

In [30]:
import string
mess = "Sample message! Notice: it has punctuation."
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [31]:
nopunc = [c for c in mess if c not in string.punctuation]
nopunc

['S',
 'a',
 'm',
 'p',
 'l',
 'e',
 ' ',
 'm',
 'e',
 's',
 's',
 'a',
 'g',
 'e',
 ' ',
 'N',
 'o',
 't',
 'i',
 'c',
 'e',
 ' ',
 'i',
 't',
 ' ',
 'h',
 'a',
 's',
 ' ',
 'p',
 'u',
 'n',
 'c',
 't',
 'u',
 'a',
 't',
 'i',
 'o',
 'n']

In [32]:
nopunc = ''.join(nopunc)
nopunc

'Sample message Notice it has punctuation'

In [33]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/oem/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [34]:
nopunc.split()

['Sample', 'message', 'Notice', 'it', 'has', 'punctuation']

In [35]:
clean_mess = [word for word in nopunc.split() if word.lower() not in
stopwords.words('english')]

In [36]:
clean_mess

['Sample', 'message', 'Notice', 'punctuation']

In [37]:
def text_process(mess):
    nopunc=[char for char in mess if char not in string.punctuation]
    nopunc="".join(nopunc)
    return[word for word in nopunc.split() if word.lower() not in stopwords.words("english")]
messages.head()

                                               label  message
0                                           v1,v2,,,      NaN
1  ham,"Go until jurong point, crazy.. Available ...      NaN
2               ham,Ok lar... Joking wif u oni...,,,      NaN
3  spam,Free entry in 2 a wkly comp to win FA Cup...      NaN
4  ham,U dun say so early hor... U c already then...      NaN

In [43]:
messages = pd.read_csv("spam.csv", encoding="latin-1")

In [44]:
messages.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [45]:
messages["message"] = messages["v2"]

In [46]:
bow_transformer = CountVectorizer(analyzer=text_process).fit(messages["message"])

In [47]:
print(len(bow_transformer.vocabulary_))

11304

In [48]:
mess4=messages['message'][6]
print(mess4)

Even my brother is not like to speak with me. They treat me like aids patent.

In [49]:
bow4=bow_transformer.transform([mess4])
print(bow4)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 7 stored elements and shape (1, 11304)>
  Coords	Values
  (0, 1777)	1
  (0, 4512)	1
  (0, 5111)	1
  (0, 7698)	2
  (0, 8653)	1
  (0, 9860)	1
  (0, 10513)	1

In [50]:
bow_transformer.get_feature_names_out()[7800]

'lotta'

In [51]:
messages_bow=bow_transformer.transform(messages['message'])
print('shape of sparsee matrix:',messages_bow.shape)

shape of sparsee matrix: (5572, 11304)

In [52]:
messages_bow.nnz

50193

In [53]:
from sklearn.feature_extraction.text import TfidfTransformer

In [54]:
tfidf_transformer=TfidfTransformer().fit(messages_bow)
tfidf4=tfidf_transformer.transform(bow4)

print(tfidf4)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (1, 11304)>
  Coords	Values
  (0, 1777)	0.33521441416639297
  (0, 4512)	0.43692878744892083
  (0, 5111)	0.3383712690711893
  (0, 7698)	0.4149098236609654
  (0, 8653)	0.43692878744892083
  (0, 9860)	0.32680848361658965
  (0, 10513)	0.33521441416639297

In [56]:
messages["label"] = messages["v1"]
messages["message"] = messages["v2"]

In [57]:
from sklearn.model_selection import train_test_split

msg_train, msg_test, label_train, label_test = train_test_split(
    messages["message"], messages["label"], test_size=0.2, random_state=42
)

In [58]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

pipeline = Pipeline([
    ("bow", CountVectorizer(analyzer=text_process)),
    ("tfidf", TfidfTransformer()),
    ("classifier", MultinomialNB())
])

pipeline.fit(msg_train, label_train)

predictions = pipeline.predict(msg_test)

print(classification_report(label_test, predictions))

              precision    recall  f1-score   support

         ham       0.96      1.00      0.98       965
        spam       1.00      0.75      0.85       150

    accuracy                           0.97      1115
   macro avg       0.98      0.87      0.92      1115
weighted avg       0.97      0.97      0.96      1115

In [59]:
from sklearn import svm

pipeline1 = Pipeline([
    ("bow", CountVectorizer(analyzer=text_process)),
    ("tfidf", TfidfTransformer()),
    ("classifier", svm.SVC(kernel="linear"))
])

pipeline1.fit(msg_train, label_train)

predictions1 = pipeline1.predict(msg_test)

print(classification_report(label_test, predictions1))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       965
        spam       0.99      0.89      0.93       150

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115